### ISSUE TITLE
UnboundLocalError: cannot access local variable 'v2' where it is not associated with a value

### ISSUE THREAD

**Issue by febaac** [rogsme/ute_homeassistant_integration#1]
Hola Roger.
Perdón pero es mi primera vez aportando 'errores' .
Quizás estoy haciendo algo mal durante la instalación.
Esto me devuelve el log de HA.

##############################################

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:575
Integration: Sensor (documentation, issues)
First occurred: 17:50:04 (1 occurrences)
Last logged: 17:50:04

ute: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 575, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 961, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ute/sensor.py", line 87, in update
    ute_data = self.client.get_current_usage_info()["data"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ute_wrapper/ute.py", line 305, in get_current_usage_info
    power_in_watts = self._convert_triphasic_powers_to_power_in_watts(readings)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ute_wrapper/ute.py", line 267, in _convert_triphasic_powers_to_power_in_watts
    power_2_in_watts = v2 * i2 * power_factor
                       ^^
UnboundLocalError: cannot access local variable 'v2' where it is not associated with a value

![image](https://github.com/rogsme/ute_homeassistant_integration/assets/7883997/948101fb-4930-4716-a7c8-ab2d25a31836)

**Comment by rogsme** [comment]
Hola! Muchas gracias por el reporte!

Es raro porque deberia de funcionar con sistemas trifasicos. Que plan de UTE tienes?

**Comment by febaac** [comment]
De nada! 

![Screenshot_2023-12-12-18-31-39-206_foo bar UTEApp](https://github.com/rogsme/ute_homeassistant_integration/assets/7883997/39d3ad77-f63a-47ab-86f2-8077792212a2)

**Comment by rogsme** [comment]
Ahh, ya vi el problema! Tu plan es Monofasico, el mio (el que use para probar) es Trifasico

![image](https://github.com/rogsme/ute_homeassistant_integration/assets/1617177/304d84b5-ecb6-4604-a545-ff123ffbe9fc)

Realmente no sabria como hacer debugging a esto... Necesitaria acceso a alguna cuenta con un plan Monofasico o (si sabes programar) que tu mismo hagas los cambios y los agregues al repositorio del wrapper aqui: https://gitlab.com/rogs/ute

**Comment by febaac** [comment]
Voy a intentarlo, en la noche o mañana. Sino le paso la data a un compañero que la tiene más clara.

Gracias!

**Comment by rogsme** [comment]
Perfecto! Voy a investigar un poco hoy, pero me ayudaria muchisimo si podrian darme mas info. Gracias!

**Comment by aronkahrs-us** [comment]
en `get_current_usage_info` cambiar:
`power_in_watts = self._convert_triphasic_powers_to_power_in_watts(readings)`
por:
` if self.get_account()["agreementInfo"]["serviceType"].lower() == 'monofasico':
      power_in_watts = self._convert_monophasic_power_to_power_in_watts(readings)
  else:
      power_in_watts = self._convert_triphasic_powers_to_power_in_watts(readings)`
agregar:
`
def _convert_monophasic_power_to_power_in_watts(self, readings: List[dict]) -> float:

        for reading in readings:
            reading_type = reading["tipoLecturaMGMI"]
            if reading_type == "I1":
                i1 = float(reading["valor"])
            elif reading_type == "V1":
                v1 = float(reading["valor"])

        power_factor = self.power_factor or 1

        power_1_in_watts = v1 * i1 * power_factor

        return round(power_1_in_watts, 3)`

**Comment by rogsme** [comment]
Esa sugerencia romperia el trifasico. Lo ideal es hacer que funcione para trifasico y bifasico tambien. Ya estoy trabajando en un parche, en una hora lo tendre listo!

**Comment by aronkahrs-us** [comment]
No pensé en la bifasica, pero eso chequea en la cuenta el tipo de conexion y calcula dependiendo del tipo. no me doy cuenta si afecta al trifasico, mi conexion es monofasica.
Suerte, saludos!

**Comment by rogsme** [comment]
Acabo de publicar una nueva version ([1.2.0](https://github.com/rogsme/ute_homeassistant_integration/releases/tag/1.2.0)). Puedes probar ahora! @febaac

**Comment by febaac** [comment]
Funciona! Me devuelve información, luego debo chequear que sea correcta. Gracias!

**Comment by rogsme** [comment]
@febaac Que bueno saber que funciona!

Recuerda configurar tu factor de potencia. UTE no lo dice por ningun lado (o al menos no lo he conseguido!). En mi experiencia, un buen factor de potencia es entre 0.9 y 1.0. Te toca jugar un poco con los valores
