### ISSUE TITLE
Possible capping of API calls

### ISSUE THREAD

**Issue by aronkahrs-us** [rogsme/ute_homeassistant_integration#2]
This morning I tried to check the energy consumption and to my surprise the integration _(not this one, but it will probably affect it as well)_ wasn't working, I tried to reload it and still it was not working so i checked the logs and found this:
- `('Send reading request return status: 429, reason: Too Many Requests, content: API calls quota exceeded! maximum admitted 10 per 1d.',)`
- `('Send reading request return status: 429, reason: Too Many Requests, content: API calls quota exceeded! maximum admitted 2 per 5m.',)`
- `('Login return status: 429, reason: Too Many Requests, content: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>429 Too Many Requests</title>\n</head><body>\n<h1>Too Many Requests</h1>\n<p>The user has sent too many requests\nin a given amount of time.</p>\n</body></html>\n',)`

Apparently now there is a limit of 2 calls per 5 minutes and 10 calls per day or at least thats what the error says, so this potentially breaks the integration.

**Comment by rogsme** [comment]
Yes, I was just debugging this. I guess UTE broke this and all integrations 😞 I will look for possible solutions, but it doesn't look too good. Thank you for the report @aronkahrs-us!

**Comment by aronkahrs-us** [comment]
Seems like it yes, a potential solution can be loading past consumptions, UTE allows to get a json with past data.

**Comment by rogsme** [comment]
That could be one, yes, but then it wouldn't be a live service. The integration would have to change a lot to make it historic instead of live

**Comment by aronkahrs-us** [comment]
For sure, but it's a great service one wouldn't like to lose. I'm writing a email to UTE enquiring abut this, for us, issue, i don't expect them to change anything but to tell us the reasoning behind, i'll update when, and if, they reply.

**Comment by rogsme** [comment]
Oh, that's great! Thank you for that!

**Comment by aronkahrs-us** [comment]
One possible cause of this is the apparent transition to a new app
![UTE Play Store](https://github.com/rogsme/ute_homeassistant_integration/assets/85702110/d7580614-8c6d-470a-bdb3-1d327c5dff66)

**Comment by rogsme** [comment]
Hmmm... That makes sense. I guess we would have to wait to see this new app and try to reverse engineer it, just like I did with [ute](https://gitlab.com/rogs/ute). I'll try looking for another solution later on this week, but if you have any other updates, please let me know! 👍🏾

**Comment by aronkahrs-us** [comment]
I'm about to do that, but i don't expect to find anything different, based on the new app behavior

**Comment by aronkahrs-us** [comment]
I'm having a really hard time trying to capture the api requests, by the few i could capture i'm guessing that they are using the same still, but not sure for how long

**Comment by rogsme** [comment]
They might be using the same one, but just rate limiting it. I'm going to do some research this weekend, but everything points to this integration being dead, at least in the current state (real time) 😞 

Let me know if they answer your emails asking about this, but let's hope that if they are really creating a new API, it allows for this type of integrations

**Comment by aronkahrs-us** [comment]
https://github.com/gustavoqzdaa/ute_energy/issues/10#issuecomment-1869904220
this may be useful

**Comment by matbott** [comment]
Buen dia Roger.
Recien encontre este complemento para HA. pero entiendo por este caso que no esta funcionando? es correcto?
Saludos.

**Comment by rogsme** [comment]
Es correcto @matbott. En este momento no funciona por bloqueos de la app de UTE (rate limiting). Todas las pruebas que he hecho hasta el momento han sido fallidas, parece que desde UTE se estan preparando para lanzar una app nueva. Asumo que cuando ellos lancen esa app, podemos hacer otra ingeniería inversa y sacar la información para HomeAssistant

**Comment by aronkahrs-us** [comment]
Hasta ahora probé decompilando la apk nueva e interceptando los paquetes http. De la apk no pude sacar nada util y a diferencia de la app actual (que no es muy segura) la nueva no funciona a traves de un proxy, no he logrado interceptar ningun paquete.

**Comment by rogsme** [comment]
Algo raro empezo a suceder hoy con el API 🤔 Tiene mas o menos una hora y media funcionando sin problemas y sin ningun cambio. Probalbemente quitaron el cap? 

<img width="583" alt="image" src="https://github.com/rogsme/ute_homeassistant_integration/assets/1617177/faeba429-acf5-45c8-a406-44c6aa096b5b">
