### ISSUE TITLE
No funciona

### ISSUE THREAD

**Issue by aldor443** [rogsme/ute_homeassistant_integration#3]
Y como se supone que lea el consumo si no tiene dato alguno, ni de cuenta UTE
Entonces ??

**Comment by rogsme** [comment]
Hola!

La integración si funciona, pero dejará de funcionar pronto. Usa el API de la APP vieja de UTE, "UTE" (no "UTE Clientes"):

![Screenshot_20240414_230402_One UI Home.jpg](https://github.com/rogsme/ute_homeassistant_integration/assets/1617177/c18b95e6-6c81-4d06-a669-34f19a839375)

La única manera de autenticarte era a través de un mensaje de texto (nada de username/password). En la ingeniería inversa descubrí que la autenticación es opcional, lo que es un error grande de parte de UTE, asumo que por eso van a invalidar esa API y solo se puede usar la APP nueva. Puedes leer más sobre la ingeniería inversa aqui: https://gitlab.com/rogs/ute

Lamentablemente la app original de UTE ya no existe más y si no tuviste cuenta allí no vas a poder usar la integración. Igualmente, como te dije antes UTE va a apagar la integración pronto. 

![Screenshot_20240414_230003_UTE.jpg](https://github.com/rogsme/ute_homeassistant_integration/assets/1617177/b567a9d0-eac8-47f4-836e-351ac15baae3)
