### ISSUE TITLE
Se podria corregir para que funcione?

### ISSUE THREAD

**Issue by oribe522** [rogsme/ute_homeassistant_integration#4]
Se podria corregir para que funcione?, estaria bueno es re util!

**Comment by rogsme** [comment]
Lamentablemente no, UTE elimino el API que estaba usando. La única forma de arreglarlo seria haciendo otra ingeniería inversa a la nueva app de UTE, pero ni siquiera estoy seguro que traiga la información del uso actual, al menos no la veo en la app
